trigger:
- main

pool:
  name: default

stages:
  - stage: VersionBump
    pool:
      name: default
      demands: Web
    displayName: Version Bump
    jobs:
      - job: VersionBumpJob
        displayName: VersionBump
        steps:
          - checkout: self
            persistCredentials: true

          - task: CmdLine@2
            displayName: "Pull Latest Changes"
            inputs:
              script: |
                git config --global user.email "buildAgent@gsd-software.com"
                git config --global user.name "Build Agent"
                git pull origin $(Build.SourceBranchName)
          
          - powershell: |
              $buildName = & "C:\Users\buildagent\AppData\Local\Pub\Cache\bin\cider" bump patch
              Write-Host "Output from cider command: $buildName"
              Write-Host "##vso[build.updatebuildnumber]$buildName"
            displayName: 'Bump Version and Set Build Name'
            condition: eq(variables['Build.SourceBranch'], 'refs/heads/main')

          - task: CmdLine@2
            displayName: 'Set Git Config and Push Version Change'
            condition: eq(variables['Build.SourceBranch'], 'refs/heads/main')
            inputs:
              script: |
                git commit -a -m "Vesion patch [skip ci]"
                git tag -a $(Build.BuildNumber) -m "Version $(Build.BuildNumber)"
                git config --global user.email "buildAgent@gsd-software.com"
                git config --global user.name "Build Agent"
                git push origin HEAD:$(Build.SourceBranchName) --tags
                git push --set-upstream origin HEAD:$(Build.SourceBranchName)

  - stage: PublishPackage
    pool:
      name: default
      demands: Pub
    displayName: Publish to pub.dev
    dependsOn: VersionBump
    condition: eq(variables['Build.SourceBranch'], 'refs/heads/main')
    jobs:
      - job: PublishJob
        displayName: Publish Package
        steps:
          - checkout: self
            persistCredentials: true

          - task: CmdLine@2
            displayName: "Pull Latest Changes"
            inputs:
              script: |
                git config --global user.email "buildAgent@gsd-software.com"
                git config --global user.name "Build Agent"
                git pull origin $(Build.SourceBranchName)

          - task: CmdLine@2
            displayName: "Publish to pub.dev"
            inputs:
              script: |
                flutter pub publish --force

  - stage: SyncGitHub
    pool:
      name: default
      demands: Web
    displayName: Sync to GitHub
    dependsOn: PublishPackage
    condition: eq(variables['Build.SourceBranch'], 'refs/heads/main')
    jobs:
      - job: SyncJob
        displayName: Sync to GitHub
        steps:
          - checkout: self
            persistCredentials: true
            fetchDepth: 0  # Fetch complete history

          - task: CmdLine@2
            displayName: "Setup Git and Force Push to GitHub"
            env:
              GITHUB_TOKEN: $(GITHUB_TOKEN)
            inputs:
              script: |
                git config --global user.email "buildAgent@gsd-software.com"
                git config --global user.name "Build Agent"
                git config --global push.default simple
                git remote remove github 2>nul || echo "Remote doesn't exist"
                git remote add github https://$(GITHUB_TOKEN)@github.com/GSD-Software-mbH/GSD-RestAPI.git
                git fetch --all --tags
                git branch -a
                git push github HEAD:main --force --tags
                echo "Successfully force-pushed complete branch to GitHub"